### ISSUE TITLE
wrapping in Q defers/promises

### ISSUE THREAD

**Issue by gr2m** [elmarburke/hoodie-plugin-angularjs#1]
First of all, I love the idea to use a hoodie plugin to provide an angular service. We should do the same for all the JS MC\* frameworks out there.

I wonder why you do this

``` js
    this.findAll = function (search) {
      var deferred = $q.defer();

      hoodie.store.findAll(search)
        .done(function (objects) {
          deferred.resolve(objects);
        });

      return deferred.promise;
    };
```

instead of doing this

``` js
    this.findAll = hoodie.store.findAll
```

**Comment by ajoslin** [comment]
I'm working on this :)

**Comment by elmarburke** [comment]
It's because angular use its own promises with some **magic** (as far as i found out until now)

**Comment by robinboehm** [comment]
AngularJS needs to to scope 'magic' because of the dirty checking algo.
But you just can wrap this in a $q.when()

https://docs.angularjs.org/api/ng/service/$q#when
