### ISSUE TITLE
Adding to hoodieArray not populating couchdb

### ISSUE THREAD

**Issue by redgeoff** [elmarburke/hoodie-plugin-angularjs#10]
I would just like to say that your plugin is awesome!

If you run the following code and then look in couchdb, you'll see that the new item hasn't been added. If you use hoodie.store.add() directly then it appears to work, but I think there is a problem with adding new items via your plugin. (Your plugin appears to update items fine). I briefly tried to debug this, but haven't found the problem yet and was hoping that someone may have some insight. I think it may have something to do with the item being stored in local storage and then flagged improperly so that hoodie doesn't send the new data to couchdb.

``` html
<!DOCTYPE html>
<html ng-app="todos">
  <head>
    <meta charset="utf-8">
    <title>Todos</title>
  </head>
  <body>

    <h2>Todos</h2>
    <div ng-controller="TodoCtrl">
      <ul ng-model="todos">
        <li ng-repeat="todo in todos">
          <span>{{todo.txt}}</span>
        </li>
      </ul>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.4/angular.min.js"></script>
    <script src="/_api/_files/hoodie.js"></script>
    <script>

      var hoodie  = new Hoodie();
      window.hoodie = hoodie;

      hoodie.account.signUp('joe@example.com', 'secret');
      hoodie.account.signIn('joe@example.com', 'secret');

      angular.module('todos', ['hoodie'])

      .config(function(hoodieProvider) {
        hoodieProvider.url('http://127.0.0.1:6001');
      })

      .controller('TodoCtrl', function ($scope, hoodieArray) {

        hoodieArray.bind($scope, 'todos', 'todo');

        $scope.todos.push({txt: 'take out trash'});

        $scope.todos.push({txt: 'clean dishes'});

      });

    </script>
  </body>
</html>
```

**Comment by elmarburke** [comment]
Hey Geoff,
thanks for you flowers! I think it has to do with CORS since you use a specific url.
Could you try this

``` javascript
      .controller('TodoCtrl', function ($scope, hoodieStore) {
        hoodieStore.('todo', {txt: 'clean dishes'})
      })
```

**Comment by redgeoff** [comment]
Thanks for the tip, but I'm trying to use angular conventions to push to the todos array, e.g.

``` javascript
$scope.todos.push({txt: 'take out trash'});
```

If I use

``` javascript
hoodieStore.add('todos', {txt: 'clean dishes'});
```

then everything appears to work, but that defeats the purpose of using angular.

I also tried using

``` javascript
hoodieProvider.url('/');
```

just in case it was a CORS issue and that didn't appear to help either.

Is it possible that you angular binding is disabling the "dirty" flag used by hoodie to sync new data?

Do you have any fully functioning code using your binding that demonstrates adding new data to the scope?

**Comment by redgeoff** [comment]
I just submitted a pull request (https://github.com/elmarburke/hoodie-plugin-angularjs/pull/13) that should fix this.
