### ISSUE TITLE
Utilizing omnibinder

### ISSUE THREAD

**Issue by redgeoff** [elmarburke/hoodie-plugin-angularjs#11]
I think it would be really cool if we modified the plugin to use omnibinder (https://github.com/jeffbcross/omnibinder). Any thoughts? When I get some free time, I'll try to help out with this.

**Comment by elmarburke** [comment]
Could you say a few words about whats better when we use [omnibinder](https://github.com/jeffbcross/omnibinder)? I like to hold the dependencies as low as possible, but if there is a good point, we should used it.

**Comment by redgeoff** [comment]
Sure, in my mind the objective would be to write one angular controller that would work with any backend: hoodie, firebase, REST, etc... Hoodie is great but it won't always be the best choice for every project.

I think my suggestion would be to write an omnibinder protocol that works with hoodie, but now that I think more about it, it probably makes sense that this protocol would instead be a contribution to the omnibinder project.

**Comment by robinboehm** [comment]
hehe, yes I think that make more sense! :)
But thx for your thoughts =)
