### ISSUE TITLE
hoodiePromiseFnWrap Broken

### ISSUE THREAD

**Issue by OClement** [elmarburke/hoodie-plugin-angularjs#27]
Doing: `hoodieAccount.on('authenticated', function() { ... });`
Throws: `TypeError: Cannot read property 'then' of undefined`

This calls `hoodiePromiseFnWrap`:

`context[fnName].apply(context, args).then(angularDigestFn($rootScope, deferred.resolve), angularDigestFn($rootScope, deferred.reject));`

This line expects `context[fnName]` to return a promise, but it doesn't.

Using Hoodie 0.8.2

This is the source of the method called (in hoodie.js):

```
function bind(ev, callback) {
    var evs, name, _i, _len;

    evs = ev.split(' ');

    for (_i = 0, _len = evs.length; _i < _len; _i++) {
        name = namespace + evs[_i];
        hoodie.eventsCallbacks[name] = hoodie.eventsCallbacks[name] || [];
        hoodie.eventsCallbacks[name].push(callback);
    }
}
```

**Comment by robinboehm** [comment]
We're currently in a refactoring process.
This line should be solve the problem without exceptions:

https://github.com/elmarburke/hoodie-plugin-angularjs/pull/23/files#diff-87db059559893e5a18a8b505b9f40781R11

I'll keep the issue open to check the case once we've merged the refactoring.
thx @OClement

**Comment by OClement** [comment]
Great news, thanks for the update

I'm just starting playing with Hoodie, integrating it in an dummy Angular App so far
This "plugin" definitely help get things right, looking forward for the patch!

**Comment by robinboehm** [comment]
Solved via https://github.com/elmarburke/hoodie-plugin-angularjs/commit/957100f678c17e4b52cbcfedae221889942c4ac7
