### ISSUE TITLE
getting back updated records

### ISSUE THREAD

**Issue by ssp** [elmarburke/hoodie-plugin-angularjs#31]
I am trying to display / edit some CouchDB documents and using Hoodie and angular in in the process.

Documents display just fine. I can also edit documents. But I can only do that once.

The problem I seem to have is that hoodie-plugin-angularjs will write my edited document back to Hoodie but the document is not updated in the array I have in my model. As a consequence it will not have the latest _rev and the second edit will fail.

I can’t really figure out at this stage whether I’m doing something in a wrong way here or whether this is an issue with hoodie-plugin-angularjs.

A simple example is given by this controller which objects of type `test` to the `items` variable in its scope. It also provides a function to edit a field in the document.

``` js
testApp.controller('items', ['$scope', 'hoodieArray', function ($scope, hoodieArray) {
    $scope.personen = [];           
    hoodieArray.bind($scope, 'items', 'test');

    $scope.updateItem = function (theItem) {
        if (theItem.count === undefined) {
            theItem.count = 0;
        }
        theItem.count++;
    };
}]);
```

using it with this angular template

``` html
<ul class="list-group" ng-controller="items">
    <li ng-repeat="item in items track by item.id"
        class="list-group-item">
        <a ng-click="updateItem(item)" href="">
            {{item.id}}
            ({{item.count}})
            {{item._rev}}
        </a>
    </li>
</ul>
```

… I would expect to get a list of clickable items displaying the id / count / _rev of each document. Clicking a document will edit it by incrementing the count. This change will be stored by hoodie, creating a new _rev value in the process and that change will be reflected in the list.

The behaviour I am seeing, however, is that the count does increase but the _rev field does not. Hence my suspicion that something unexpected is going on.

**Comment by robinboehm** [comment]
Thx for your help @ssp :)))
Could you write down your expectation as a test?
https://github.com/elmarburke/hoodie-plugin-angularjs/blob/master/test/hoodieArray.spec.js

**Comment by ssp** [comment]
I’m afraid I am not really familiar with the test framework and the intricacies of reducing my example to its environment.

The closest I could get would be this:

``` js
  describe('ssp', function () {
    it ('should be able to bind to two scope variables', function () {
      $rootScope.store1 = [];
      hoodieArray.bind($rootScope, 'test', 'store1');

      $rootScope.store1.push({'count': 0});

      $rootScope.store2 = [];
      hoodieArray.bind($rootScope, 'test', 'store2');
      $rootScope.$apply();

      expect($rootScope.store1).toBe($rootScope.store2);
    })
  });
```

but my impression is that this may be a different issue as the store2 variable seems to remain empty:

```
    Error: Expected [ { count : 0 } ] to be [  ].
```

**Comment by robinboehm** [comment]
Hey @ssp ,
Thx! I think I got your point.
Will validate this today ...

**Comment by robinboehm** [comment]
Records are updated here:
https://github.com/elmarburke/hoodie-plugin-angularjs/blob/master/src/hoodieArray.js#L53-L58

I've got not _rev attribute, but a _updatedAt_ value from the server.
So server correct updates. Are you sure that your server updates the _rev value and return in in the response.

I hope that helps you, If not just comment and I reopen the issue.

Rob
