### ISSUE TITLE
$watch listener will not triggered if $state.go() immediately after changing scope object

### ISSUE THREAD

**Issue by merlinran** [elmarburke/hoodie-plugin-angularjs#33]
``` js
$scope.save = function() {
  $scope.tasks.push($scope.taskToModify);
  $state.go('index');
};
```

will not sync `$scope.tasks` to Hoodie, as [`$scope.$watch()` listener](https://github.com/elmarburke/hoodie-plugin-angularjs/blob/master/src/hoodieArray.js#L17) has no opportunity to be called.

I do have a workaround but not so obvious:

``` html
<button ng-click="save()" ui-sref="index">
```

As the scope object bound is always an Array, is it possible to override Array methods? Or are there other alternatives?

**Comment by robinboehm** [comment]
You should hold your data in a data-service not only via controller/hoodie bindings.
I think that solves the problem with to early destroyed hoodieArray binding.

Thx @merlinran 
If that doesn't solve your problem, just ping me! :)
