### ISSUE TITLE
Get CoverAll up and running

### ISSUE THREAD

**Issue by robinboehm** [elmarburke/hoodie-plugin-angularjs#34]
- [x] add the badge
- [x] Get a Token
- [ ] Add the token to the env vars (https://github.com/elmarburke/hoodie-plugin-angularjs/pull/24)

**Comment by elmarburke** [comment]
What are the next steps? Maybe @boennemann can give a hint?

**Comment by boennemann** [comment]
``` bash
gem install travis
cd hoodie-plugin-angularjs
travis encrypt COVERALLS_REPO_TOKEN={THE_ACTUAL_TOKEN} --add
git add .travis.yml
git commit -m 'chore(travis): add coveralls token'
```

should suffice ;) 

please ping me again, if not

**Comment by elmarburke** [comment]
Done as described, but it's currently not reporting. Must I add https://www.npmjs.org/package/coveralls? 
https://travis-ci.org/elmarburke/hoodie-plugin-angularjs/builds/31634852

**Comment by boennemann** [comment]
The actual reporting is needed (guess I added that to grunt before).

Using https://www.npmjs.org/package/gulp-coveralls and running it after success should suffice.

```
npm install --save-dev gulp-coveralls
```

``` js
var coveralls = require('gulp-coveralls');

gulp.src('test/coverage/**/lcov.info')
  .pipe(coveralls());
```

and append this to travis: 

```
after_success:
- gulp coveralls
```
