### ISSUE TITLE
Callback after successful bind

### ISSUE THREAD

**Issue by redgeoff** [elmarburke/hoodie-plugin-angularjs#35]
I'm trying to execute some code after `hoodieArray.bind` successfully binds to `$scope`. I'm considering something like:

``` javascript
service.bind = function ($scope, key, hoodieKey, afterBind) {
....
hoodieStore.findAll(hoodieKey).then(function (data) {
  $scope[key] = data;
  if (afterBind) afterBind(); \\ callback
 });
```

Should I code up a PR? Is there a better way of handling this via promises?

My ultimate goal is to bind an _edit_ view's `$scope` to an element in the array and not just the entire array, but I believe this binding needs to take place after the full array has been bound.

**Comment by elmarburke** [comment]
Hey @redgeoff, 
i guess you can use hoodieObject for that. 
https://github.com/elmarburke/hoodie-plugin-angularjs#hoodieobject

Let me know it it works for you!

Cheers,
  Elmar
