### ISSUE TITLE
Example of using Dependency Injection for hoodieStore

### ISSUE THREAD

**Issue by steve21124** [elmarburke/hoodie-plugin-angularjs#36]
Do you have snippet example of using Dependency Injection for hoodieStore? 

thanks and sorry if it is a little bit basic :)

**Comment by elmarburke** [comment]
You can find a very basic example here: 
https://github.com/elmarburke/hoodie-plugin-angularjs#hoodiearraybindscope-store-hoodiestore 

If you want to start with angular, https://egghead.io/tags/free is a really good starting point ;)

If you have any questions feel free to open a new issue :)

Cheers,
  Elmar
