### ISSUE TITLE
Tag 0.1.1 release

### ISSUE THREAD

**Issue by Sjors** [elmarburke/hoodie-plugin-angularjs#41]
That way I can do:

``` sh
bower install https://github.com/elmarburke/hoodie-plugin-angularjs.git#0.1.1 --save
```

**Comment by elmarburke** [comment]
Sorry for my late response!
What exactly is your issue? Does the installation of the plugin didn't work correctly?
I recommend you to install the plugin as hoodie plugin, then everything is in the right order.

```
$ hoodie install angularjs
```

Groetjes, Elmar

**Comment by Sjors** [comment]
It wasn't a question, but a bug report. If you look a the list of tags here: https://github.com/elmarburke/hoodie-plugin-angularjs/releases

There is no tag for 0.1.1, which is what caused bower to fail. I guess if I use "hoodie install" instead it won't be an issue.

**Comment by elmarburke** [comment]
Ok, I get the point. The tags are added, you shouldn't have problems now with bower :smile:
