### ISSUE TITLE
Having problems with adding new data to store

### ISSUE THREAD

**Issue by idanb11** [elmarburke/hoodie-plugin-angularjs#44]
Hi @elmarburke , great great work. :+1: 

I'm having some problems with adding new data to hoodie store, I'm getting the following errors:
`GET http://127.0.0.1:6004/_api/user%2Ffc9ofwf/_changes?include_docs=true&since=0 401 (Unauthorized)`
`jquery.js:8625 n.ajaxTransport.k.cors.a.crossDomain.send`
`jquery.js:8161 n.extend.ajaxhoodie.min.js:6 ohoodie.min.js:7 h.request`
`hoodie.min.js:7 h.pullhoodie.min.js:7 h.bootstrap`
`hoodie.min.js:7 h.connecthoodie.min.js:6 d.connecthoodie.min.js:6 f`
`hoodie.min.js:6 djquery.js:3251 (anonymous function)`
`jquery.js:3094 n.Callbacks.j`
`jquery.js:3140 n.Callbacks.k.addjquery.js:3250 (anonymous function)`
`jquery.js:374 n.extend.each`
`jquery.js:3247 (anonymous function)`
`jquery.js:3307 n.extend.Deferred`
`jquery.js:3246 n.extend.Deferred.d.then`
`hoodie.min.js:6 (anonymous function)`
`jquery.js:3251 (anonymous function)`
`jquery.js:3094 n.Callbacks.jjquery.js:3206 n.Callbacks.k.fireWith`
`jquery.js:3258 (anonymous function)`
`jquery.js:3094 n.Callbacks.j`
`jquery.js:3206 n.Callbacks.k.fireWith`
`jquery.js:8259 xjquery.js:8600 n.ajaxTransport.k.cors.a.crossDomain.send.b`

`GET http://127.0.0.1:6004/_api/_users/org.couchdb.user%3Auser%2Ftest 404 (Not Found)`

I looks like it is related to CORS (crossDomain), I'm using the default hoodie Provider:
`hoodieProvider.url('/');` in the agnular module config.

Please help solving this issue.
Thanks,
Idanb11

**Comment by idanb11** [comment]
One more error that i see:
`Unhandled promise rejection Promise {_isHoodiePromise: true, done: function, fail: function, always: function, progress: function…}`
`_isHoodiePromise: true`
`_progressCallbacks: Array[0]`
`always: function always(callback) {`
`catch: function catch_(error) {`
`done: function done(callback) {`
`fail: function fail(callback) {`
`progress: function progress(callback) {`
`then: function (onResolve, onReject) {__proto__:`
`Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: HoodieErrorconstructor: function HoodieError(properties) {message: ""_design" is invalid object type. lowercase letters, numbers and dashes allowed only. Must start with a letter."name: "HoodieObjectTypeError"rules: "lowercase letters, numbers and dashes allowed only. Must start with a letter"stack: (...)type: "_design"__proto__: Error`

Idanb11

**Comment by elmarburke** [comment]
Thanks @idanb11 :blush:, nice to hear that you like it!

1) This error looks like an Hoodie error. I guess the people at hoodiehq/faq#83 will help you!

2) Yea, there is an unhandled rejection of an promise. This is not an error of the adapter, just add an errorCallback to you .then-function and handle the error. You'll find more information about promises in Angular on https://docs.angularjs.org/api/ng/service/$q

I'll close this issue because it has nothing to do with this plugin directly. Thanks for reporting anyway, keep on building with hoodie!!!
