### ISSUE TITLE
Don't dirty the global scope

### ISSUE THREAD

**Issue by robinboehm** [elmarburke/hoodie-plugin-angularjs#6]
Many places defining variables on the global scope.
We should clear that.

``` js
var hoodieModule
//...
function hoodieEventWrap(hoodieInstance, eventName, $rootScope,  fn) {
//...
function hoodiePromiseFnWrap(context, fnName, $q, $rootScope) {
//...
function angularDigestFn($rootScope, callback) {
//...
var HOODIE_URL_ERROR = 
```

I've started this locally, should I send you a PR?

**Comment by elmarburke** [comment]
You already started? Why shouldn't you?

**Comment by robinboehm** [comment]
@elmarburke I've started some bigger changes while doing these.
There not so many tests for all that stuff, so I can't tell if it's all okay.
I've mentioned you in a commit. Could you check this?

https://github.com/robinboehm/hoodie-plugin-angularjs/commit/e718c478c5fbd1a4481af08512e673ba3df78e57#diff-87db059559893e5a18a8b505b9f40781R17

**Comment by ajoslin** [comment]
Couldn't everything just be wrapped in a closure to stop the scope polluting?

**Comment by robinboehm** [comment]
Thx @ajoslin .
We already done this in https://github.com/elmarburke/hoodie-plugin-angularjs/pull/23
But before we change the codebase, we'll cover the current functionality with tests https://github.com/elmarburke/hoodie-plugin-angularjs/pull/25
