### ISSUE TITLE
Make init easier

### ISSUE THREAD

**Issue by robinboehm** [elmarburke/hoodie-plugin-angularjs#8]
Before:

``` js
// Init Hoodie
var hoodie  = new Hoodie()
window.hoodie = hoodie;

// Init Angular
angular.module('worldDominationApp', ['hoodie'])
```

After:

``` js
// Init Angular
angular.module('worldDominationApp', ['hoodie'])
```

We could check if window.hoodie is defined.
If this in undefined, create a new instance.

https://github.com/elmarburke/hoodie-plugin-angularjs/blob/master/src/hoodieProvider.js#L12

Would make the usage easier.

**Comment by elmarburke** [comment]
Oh, that's a bug in the docs. It's not longer required, but a

```
hoodieProivder.url('http://myhoodie.com/_api');
```

in config is required.

Do you think this is ok?

**Comment by robinboehm** [comment]
Yeah, configuration is another point.
I prefer something like:

``` js
hoodieProivder.config({
  url: 'http://myhoodie.com/_api'
});
```

But you only have one param, so ... lets talk about how to config if it's necessary. Not now ;) 

!premature optimization
